quarkus.rest-client.delivery-client.url=${DELIVERY_URL:http://localhost:8081}
quarkus.rest-client.settlement-client.url=${SETTLEMENT_URL:http://localhost:8084}
quarkus.http.port=${PORT:8020}
quarkus.log.category."com.pl.platform".level=${LOG_LEVEL:DEBUG}
quarkus.smallrye-openapi.path=/api-spec