spring.application.name=settlement
server.port=8084
server.forward-headers-strategy=framework

spring.datasource.url=jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/settlementdb
spring.datasource.username=${PG_USER:platform}
spring.datasource.password=${PG_PASSWORD:platform}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================
# JPA
# ===================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=${JPA_SHOW_SQL:false}

# ===================
# Flyway
# ===================

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ===================
# Database Pool
# ===================

spring.datasource.hikari.maximum-pool-size=${DB_POOL_MAX_SIZE:32}
spring.datasource.hikari.minimum-idle=${DB_POOL_MIN_IDLE:8}
spring.datasource.hikari.connection-timeout=${DB_CONNECTION_TIMEOUT:30000}
spring.datasource.hikari.max-lifetime=${DB_MAX_LIFETIME:1800000}

# ===================
# Logging
# ===================

logging.level.root=INFO
logging.level.com.pl.hragency=INFO

## actuator
management.endpoints.web.exposure.include=health,info

management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=never

###
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s