### create driver
POST http://localhost:8081/api/drivers
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "phoneNumber": "+48123456784"
}

> {%
    client.global.set("driverId", response.body.id);
%}

### get drivers
GET http://localhost:8081/api/drivers

> {%
    client.global.set("driverId", response.body[0].id);
%}


### create delivery
POST http://localhost:8081/api/deliveries
Content-Type: application/json

{
  "deliveryAddress": "Test A",
  "distance": 230.50,
  "pickupAddress": "Test B"
}

> {%
    client.global.set("deliveryId", response.body.id);
%}

### confirm delivery
PUT http://localhost:8081/api/deliveries/{{deliveryId}}/confirm
Content-Type: application/json


### cancel delivery
PUT http://localhost:8081/api/deliveries/{{deliveryId}}/cancel
Content-Type: application/json

### get deliveries
GET http://localhost:8081/api/deliveries

### get payments
GET http://localhost:9080/api/payments

### get payments
GET http://localhost:9080/api/payments?status=Pending

> {%
    client.global.set("paymentId", response.body[0].id);
%}

### accept/paid payments
PUT http://localhost:9080/api/payments/{{paymentId}}/accept

### decline payments
PUT http://localhost:9080/api/payments/{{paymentId}}/decline