# Run Flyway migrations automatically
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db.migration
quarkus.datasource.db-kind = postgresql

quarkus.datasource.username = ${PG_USER:platform}
quarkus.datasource.password = ${PG_PASSWORD:platform}
quarkus.datasource.reactive.url = vertx-reactive:postgresql://${PG_HOST:localhost}/notificationdb

## flyway connection
quarkus.datasource.jdbc.url=jdbc:postgresql://${PG_HOST:localhost}/notificationdb

%dev.notification.sql.log=true
%test.notification.sql.log=true
%prod.notification.sql.log=false

quarkus.http.port=${PORT:8005}